// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlenderRelease } from "./BlenderRelease";

export interface BlenderReleaseList { releases: Array<BlenderRelease>, }