// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BlenderRelease { version: Array<number>, version_detail: string, download_link: string, download_type: string, download_size: string, release_date: string, tag: string, os: string, arch: string, sha256: string, ga_label: string, }